name: Setup docsearch configuration
description: Sets up docsearch configuration by downloading it and exporting the appropriate values to the environment
branding:
  icon: 'search'
  color: 'green'
inputs:
  docsearch_url:
    description: The URL to download the docsearch-config.json Default is site.url + docsearch-config.json
    required: false
outputs:
  docsearch-config-path:
    description: The path of the docsearch configuration that was downloaded
    value: ${{ steps.setup-docsearch-config.outputs.docsearch-config-path }}
  index-name:
    description: The name of the index
    value: ${{ steps.setup-docsearch-config.outputs.index-name }}
runs:
  using: 'composite'
  steps:
    - id: setup-docsearch-config
      shell: bash
      run: |
        CONFIG_FILE=docsearch-config.json
        curl -sL -o $CONFIG_FILE $(node -p "require('fs').readFileSync('antora-playbook.yml', 'utf8').match(/^  url: (.*)/m)[1]")/docsearch-config.json
        INDEX_NAME=$(node -p "JSON.parse(require('fs').readFileSync('$CONFIG_FILE')).index_name")
        echo "docsearch-config-path=$(echo $CONFIG_FILE)" >> $GITHUB_OUTPUT
        echo "index-name=$(echo $INDEX_NAME)" >> $GITHUB_OUTPUT