name: rsync Antora Docs
description: A GitHub action that syncs Antora reference documentation using rsync with support for syncing a single version. It deploys to the docs server using the github repository in the path.
branding:
  icon: 'copy'
  color: 'green'
inputs:
  docs-username:
    description: The username to connect to the docs server
    required: true
  docs-host:
    description: The host of the docs server
    required: true
  docs-ssh-key:
    description: The ssh key used to connect to the docs-host
    required: true
  docs-ssh-host-key:
    description: The docs ssh host key used to connect to docs-host
    required: true
  dry-run:
    description: Set to false if should perform the sync, else a dry run is performed
    default: false
    required: false
  site-path:
    description: The path to the site that should be synced
    default: build/site
    required: false
runs:
  using: 'composite'
  steps:
    - id: publish-docs
      shell: bash
      run: |
        if [ -z ${{ inputs.docs-username }} ]; then
          echo 'docs-username cannot be empty'
          exit 1
        fi
        if [ -z ${{ inputs.docs-host }} ]; then
          echo 'docs-host cannot be empty'
          exit 1
        fi
        # Extract repository_name from the owner/repository_name
        GITHUB_REPOSITORY_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)
        ${{ github.action_path }}/rsync-docs.sh  "${{ inputs.docs-username }}@${{ inputs.docs-host }}" "/opt/www/domains/spring.io/docs/htdocs/$GITHUB_REPOSITORY_NAME/reference/" "${{ inputs.docs-ssh-key }}" "${{ inputs.docs-ssh-host-key }}" "${{ inputs.dry-run }}" "${{ inputs.site-path }}"
