name: Bust Cloudflare Cache for Antora Docs
description: A GitHub action that busts the Cloudflare Cache for Spring based Antora docs.
branding:
  icon: 'rotate-cw'
  color: 'green'
inputs:
  context-root:
    description: The context root of the documentation (e.g. for https://docs.spring.io/spring-security/reference/ context-root is spring-security)
    required: true
  context-path:
    description: The context path of the documentation (defaults to /reference/)
    default: '/reference/'
  cloudflare-zone-id:
    description: The cloudflare zone id
    required: true
  cloudflare-cache-token:
    description: The cloudflare cache token
    required: true
runs:
  using: 'composite'
  steps:
    - id: bust-cache
      shell: bash
      run: |
        ${{ github.action_path }}/bust-cloudflare-antora-cache.sh  "${{ inputs.context-root }}" "${{ inputs.context-path }}" "${{ inputs.cloudflare-zone-id }}" "${{ inputs.cloudflare-cache-token }}"
